inherits = "kanagawa"

"ui.virtual.inlay-hint"           = { fg = "fujiGray" }
"ui.virtual.inlay-hint.parameter" = { fg = "fujiGray" }
"ui.virtual.inlay-hint.type"      = { fg = "fujiGray" }

"ui.menu"          = { fg = "fujiWhite", bg = "sumiInk0" }
"ui.menu.selected" = { fg = "carpYellow", bg = "sumiInk3" }
"ui.menu.scroll"   = { fg = "oldWhite", bg = "sumiInk0" }

"ui.selection"         = { bg = "sumiInk3" }
"ui.selection.primary" = { bg = "sumiInk3" }
"ui.text.focus"        = { fg = "carpYellow", bg = "sumiInk3" }
