# starship.toml

add_newline = false

format = """
[┌](bold purple) $directory$git_branch$cmd_duration
[└](bold purple)$character
"""

[character]
format = '$symbol '
success_symbol = '[->](bold purple)'
error_symbol = '[┤](bold purple)[✘](bold red)[├->](bold purple)'
vimcmd_symbol = '[┤](bold purple)[N](bold green)[├->](bold purple)'
vimcmd_replace_one_symbol = '[┤](bold purple)[R](bold cyan)[├->](bold purple)'
vimcmd_replace_symbol = '[┤](bold purple)[R](bold cyan)[├->](bold purple)'
vimcmd_visual_symbol = '[┤](bold purple)[V](bold blue)[├->](bold purple)'

[directory]
read_only = " "
read_only_style = "bold bright-red"
style = "bold yellow"
truncation_symbol = "../"
truncation_length = 4
truncate_to_repo = false
