# starship.toml

add_newline = false

format = """
$directory$git_branch$cmd_duration
$character
"""

[character]
format = '$symbol '
success_symbol = '[\$](bold purple)'
error_symbol = '[\$](bold red)'
vimcmd_symbol = '[N](bold blue)'
vimcmd_replace_one_symbol = '[R](bold cyan)'
vimcmd_replace_symbol = '[R](bold cyan)'
vimcmd_visual_symbol = '[V](bold purple)'

[directory]
read_only = " "
read_only_style = "bold bright-red"
style = "bold yellow"
truncation_symbol = "../"
truncation_length = 4
truncate_to_repo = false
