# starship.toml
# ╭

# format = """
# [┌- ](bold green)\
# $directory\
# $git_branch\
# $cmd_duration
# $character
# """

format = """
[┌](bold green) $directory$git_branch$cmd_duration
[└](bold green)$character
"""

[character]
format = '$symbol '
success_symbol = '[->](bold green)'
error_symbol = '[┤](bold green)[✘](bold red)[├->](bold green)'
vimcmd_symbol = '[┤](bold green)[N](bold blue)[├->](bold green)'
vimcmd_replace_one_symbol = '[┤](bold green)[R](bold cyan)[├->](bold green)'
vimcmd_replace_symbol = '[┤](bold green)[R](bold cyan)[├->](bold green)'
vimcmd_visual_symbol = '[┤](bold green)[V](bold magenta)[├->](bold green)'

[directory]
read_only = " "
read_only_style = "bold yellow"
truncation_length = 40
truncate_to_repo = false
