theme = "kanagawa"

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"

[keys.normal."+"]
b = ":sh just build"
r = ":sh just run"

[keys.normal."_"]
b = ":sh zellij run -f -- just build"
r = ":sh zellij run -f -- just run"
