theme = "kanagawa"

# general
[editor]
scrolloff = 4
popup-border = "all"
line-number = "relative"
color-modes = true
auto-completion = true
preview-completion-insert = false

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.statusline]
left = ["mode", "spacer", "version-control", "diagnostics"]
center = ["file-name", "file-modification-indicator"]
right = ["primary-selection-length", "selections", "position"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-signature-help-docs = false
display-inlay-hints = false

[editor.indent-guides]
render = true

# move line up and down
[keys.normal]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

# Toggle some options
[keys.normal."+"]
h = ":toggle lsp.display-inlay-hints"
g = ":toggle indent-guides.render"
