[[language]]
name = "bash"
indent = { tab-width = 4, unit = "    "}

[[language]]
name = "hyprlang"
file-types = ["conf"]
indent = { tab-width = 4, unit = "    "}

[[language]]
name = "zig"
indent = { tab-width = 4, unit = "    "}

[[language]]
name = "javascript"
indent = { tab-width = 4, unit = "    "}

[[language]]
name = "c"
indent = { tab-width = 4, unit = "    "}

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "    "}

[[language]]
name = "nasm"
indent = { tab-width = 4, unit = "    "}

[[language]]
name = "gas"
indent = { tab-width = 4, unit = "    "}
