[[language]]
name = "bash"
indent = { tab-width = 4, unit = "    "}

[[language]]
name = "hyprlang"
file-types = ["conf"]
indent = { tab-width = 4, unit = "    "}

[[language]]
name = "javascript"
indent = { tab-width = 4, unit = "    "}
